### ISSUE TITLE
No comments

### ISSUE THREAD

**Issue by marschall** [jni-rs/jni-sys#11]
I noticed none of the functions have any comments. I wonder wether that is because you simply didn't get around to do it or because of licensing concerns over the specification.

The only comments for JNI functions I could find are https://docs.oracle.com/en/java/javase/11/docs/specs/jni/index.html where on the bottom it says

> Copyright © 1993, 2017, Oracle and/or its affiliates. All rights reserved.

**Comment by sfackler** [comment]
sys crates typically don’t contain documentation in my experience - you can
refer to the C library for that.
