### ISSUE TITLE
Can we consider moving this into the `jni-rs` repo

### ISSUE THREAD

**Issue by rib** [jni-rs/jni-sys#17]
Hi @sfackler,

I was hoping we might be able to discuss this issue: https://github.com/jni-rs/jni-rs/issues/407

While working on the `jni` crate there have been few things recently where I've wanted to be able consider `jni-sys` changes and I think it would also be easier / helpful if `jni-sys` were actually integrated in the same repo as the `jni` crate so any changes could be synchronized too.

Two recent issues / discussions that come to mind here are:
1. https://github.com/jni-rs/jni-rs/issues/360 (wanting to ensure all jni types implement the `Debug` trait)
2. https://github.com/jni-rs/jni-sys/issues/19 (wanting to update the definition of `jboolean` to ensure we can only store the values `1` or `0` for true and false.)

Although the `jni-sys` crate doesn't generally need much attention since the JNI spec is pretty stable there are probably other small housekeeping things like migrating from Travis CI to github actions that could also be beneficial for the project.

If you have a moment, I wonder if you could say whether you'd be ok with `jni-sys` being merged into a common repo with the `jni` crate?

This would also imply enabling me and other `jni-rs` maintainers to be able to make releases of the `jni-sys` crate, if you'd be ok with that.

I'd be happy to add you as a member to the jni-rs org too.

**Comment by sfackler** [comment]
Sure, seems reasonable to me. I sent you an invite for publish rights to jni-sys on crates.io.

We can transfer this repo into the jni-rs org or just move the code over to jni-rs/jni-rs directly - either way works for me.

**Comment by rib** [comment]
Great, thanks for the response @sfackler 

Initially moving the repo to the `jni-rs` org sounds like the better starting point to me. That way we can also more easily take care of leaving a sign post in the repo as to where it has moved once we merge it into the `jni-rs` repo.

I've sent you an invite to the `jni-rs` org, which I think should enable you to transfer the repo.

**Comment by sfackler** [comment]
Done!
