### ISSUE TITLE
JNI_CreateJavaVM()

### ISSUE THREAD

**Issue by kud1ing** [jni-rs/jni-sys#2]
Do you have plans to add `JNI_CreateJavaVM()`?

**Comment by sfackler** [comment]
Feel free to open a PR adding anything that's missing!

**Comment by kud1ing** [comment]
I think it should be `fn JNI_CreateJavaVM(pvm: *mut *mut JavaVM, penv: *mut *mut c_void, args: *mut c_void) -> jint` but i am a bit lost at trying to use it: https://github.com/kud1ing/rucaja/blob/master/src/main.rs

**Comment by sfackler** [comment]
I have only personally used JNI from the other direction unfortunately.

**Comment by kud1ing** [comment]
Do you have any idea how to create a `*mut *mut` in Rust in general?

**Comment by sfackler** [comment]
For penv? From the docs it looks like that's an out pointer where JNI will place the JniEnv, so it'd look something like

```rust
let mut jvm = ptr::null_mut();
let mut env = ptr::null_mut();
let mut args = /* ... */;

let ret = JNI_CreateJavaVM(&mut jvm, &mut env as *mut _, &mut args as *mut _);
```

**Comment by kud1ing** [comment]
Thank you. It compiles now (had to change `args: *mut c_void` to `args: *mut JavaVMInitArgs` though), but gives a `Segmentation fault: 11`.

**Comment by kud1ing** [comment]
Well ok, the C++ version crashes too.

**Comment by kud1ing** [comment]
Thank you for your support. I am now able to call a Java method from Rust.

    fn JNI_CreateJavaVM(pvm: *mut *mut JavaVM, penv: *mut *mut JNIEnv, args: *mut JavaVMInitArgs) -> jint;

works for me, while the direct translation of `jni.h` would probably be

    fn JNI_CreateJavaVM(pvm: *mut *mut JavaVM, penv: *mut *mut c_void, args: *mut c_void) -> jint;

What do you think?

**Comment by sfackler** [comment]
I prefer to stick to an exact translation of what the header contains personally.

**Comment by kud1ing** [comment]
In this case i'd need to somehow overcome this error:

    casting `&mut *mut *const jni_sys::JNINativeInterface_` as `*mut *mut std::os::raw::c_void` is invalid

**Comment by sfackler** [comment]
You have to first cast to `*mut *mut *const jni_sys::JNINativeInterface_` and then to `*mut *mut c_void`.

**Comment by kud1ing** [comment]
Thanks.
