### ISSUE TITLE
Publish a new version to `crates.io`

### ISSUE THREAD

**Issue by koutheir** [jni-rs/jni-sys#27]
Can you please publish a new version, to `crates.io`, in order to allow using the latest fixes?

**Comment by rib** [comment]
For reference here, I've created this milestone to ideally roll a 0.4 release: https://github.com/jni-rs/jni-sys/milestone/1

In particular I've keen to land https://github.com/jni-rs/jni-sys/pull/28 and https://github.com/jni-rs/jni-sys/pull/23

and for the `jni` crate hopefully land: https://github.com/jni-rs/jni-rs/pull/478
